### ISSUE TITLE
peer review 29th November 2022

### ISSUE THREAD

**Issue by quavo19** [Lucash2022/Awesome_Book#2]
### hi @Lucash2022 this is your morning team 😃 
**Great work so far fulfilling all the projects requirements on this project**
## Highlights 💯 
- Good commit messages ✔️
- Professional Readme file ✔️
- Descriptive PR ✔️ 
- linters ❌ 

![happy](https://user-images.githubusercontent.com/99246359/202491301-53f8c6a2-8ff4-4337-9b6b-9c75c8bdf345.gif)
 

### Optional
[optional] you can do away with eslint errors in your JavaScript file by disabling eslint, as suggested in your project requirement.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Comment by Lucas-Erkana** [comment]
✅ Fixed this issue at [Line](https://github.com/Lucash2022/Awesome_Book/blob/84a9afaceeeec4e1bd25302e2a6af668edbfb020/.eslintrc.json#L14)

**Comment by quavo19** [comment]
### Congratulations
<img src="https://media3.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif"/>
