### ISSUE TITLE
Peer to Peer Code review Week 2 D2 (06-12-2022)

### ISSUE THREAD

**Issue by ReemMohamedAbdelfatah** [Lucash2022/Awesome_Book#7]
Hello @Lucash2022,
You have done a great job with your project so far, 
✅Followed the GitHub workflow.
✅No Linter Errors
✅great design
✅Applyed the requirements

but there are some issues you have to fix:

- [x] The footer must be at the bottom of your page. (hint: use position: fixed).
- [x] When the page reloads you can use "document.onload()" function to get the list from local storage.

Happy coding!

**Comment by Lucas-Erkana** [comment]
@ReemMohamedAbdelfatah 
Thank you for the review.
I have: 
Fixed issue [one here](https://github.com/Lucash2022/Awesome_Book/pull/9)

Fixed issue[ two here](https://github.com/Lucash2022/Awesome_Book/pull/9)
